output_dir: 'experiment/upsample/aod_4'
data:
  train_dir: data/ITS/
  test_dir: data/SOTS/indoor

model:
  in_channel: 3
  model_channel: 36

train_loader:
  num_workers: 8
  batch_size: 4
  loader: crop
  img_size: (256, 256)
  shuffle: True

test_loader:
  num_workers: 8
  batch_size: 1
  loader: default
  img_size: (600, 600)
  shuffle: False
  
optimizer:
  type: step
  total_epoch: 45
  lr: 0.0002
  T_0: 100
  T_MULT: 1
  ETA_MIN: 0.000001
  step: 15
  gamma: 0.75

hyper_params:
  x_lambda: 0.03

resume:
  flag: False
  checkpoint: None

evaluate_intervel: 5


